---
- hosts: "{{ app_hosts }}"
  become: true
  vars_files:
    - defaults/app.yml
  pre_tasks:
    - name: Ensure application name variable is defined.
      fail:
        msg: "The 'app_name' variable is not defined; please specify a unique name for each application."
      when: app_name is not defined
      tags: always
  roles:
    - name: app/user
      tags: user

    - name: app/php
      tags: php

    - name: app/nginx
      tags: nginx

    - name: app/litespeed
      tags: litespeed

    - name: app/mysql
      tags: mysql

    - name: redis
      tags: redis
      when: "'redis' in app_stack"

    - name: composer
      tags: composer
      when: "'php' in app_stack"

    - name: wpcli
      tags: wpcli
      when: "'php' in app_stack"

    - name: app/wordpress
      tags: never, wordpress

    - name: app/laravel
      tags: never, laravel

    - name: app/backup
      tags: never, backup

    - name: app/restore
      tags: never, restore

    - name: app/destroy
      tags: never, destroy
