---
- name: Create symlink in user bin folder.
  ansible.builtin.file:
    src: "/usr/bin/php{{ app_php_version }}"
    dest: "{{ app_php_path }}"
    owner: "root"
    group: "root"
    state: link

- name: Generate php-fpm pool configuration.
  ansible.builtin.template:
    src: app.conf.j2
    dest: "/etc/php/{{ app_php_version }}/fpm/pool.d/{{ app_name }}.conf"
    mode: "0644"
  notify: reload php-fpm
  when: "'php' in app_stack"

- name: Remove php-fpm configuration.
  ansible.builtin.file:
    path: "/etc/php/{{ item }}/fpm/pool.d/{{ app_name }}.conf"
    state: absent
  notify: reload php-fpm
  when: "'php' not in app_stack or item != app_php_version"
  loop: "{{ php_versions }}"
