---
- name: Generate litespeed configuration.
  ansible.builtin.template:
    src: app.conf.j2
    dest: "/usr/local/lsws/conf/vhosts/{{ app_name }}.conf"
    mode: "0644"
  notify: reload litespeed
  when: "'litespeed' in app_stack"

- name: Remove litespeed configuration.
  ansible.builtin.file:
    dest: "/usr/local/lsws/conf/vhosts/{{ app_name }}.conf"
    state: absent
  notify: reload litespeed
  when: "'litespeed' not in app_stack"
