---
- name: Generate application configuration.
  ansible.builtin.template:
    src: app.conf.j2
    dest: "/usr/local/lsws/conf/vhosts/{{ app_name }}.conf"
    mode: "0644"
  notify: reload litespeed
