---
- name: Generate nginx configuration.
  ansible.builtin.template:
    src: app.conf.j2
    dest: "/etc/nginx/sites-available/{{ app_name }}.conf"
    mode: "0644"
  notify: reload nginx
  when: "'nginx' in app_stack"

- name: Enable nginx configuration.
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ app_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}.conf"
    state: link
    force: true
  when: "'nginx' in app_stack"

- name: Remove nginx configuration.
  ansible.builtin.file:
    dest: "{{ item }}"
    state: absent
  loop:
    - "/etc/nginx/sites-enabled/{{ app_name }}.conf"
    - "/etc/nginx/sites-available/{{ app_name }}.conf"
  notify: reload nginx
  when: "'nginx' not in app_stack"
